---
ec2_image_names:
  rhel7: "RHEL-7.7_HVM_GA*x86_64*"
  rhel8: "RHEL-8.0.0_HVM_GA*x86_64*"
  centos7: "CentOS Linux 7 x86_64 HVM EBS ENA 1901_01*"
  win2016_core: "Windows_Server-2016-English-Core-Base*"
  win2016_full: "Windows_Server-2016-English-Full-Base*"
  win2019_core: "Windows_Server-2019-English-Core-Base*"
  win2019_full: "Windows_Server-2019-English-Full-Base*"

ec2_windows_instance_type: "t2.medium" 
ec2_linux_instance_type: "t2.medium" 

ec2_windows_server_ami_type: win2016_full
ec2_linux_instance_ami_type: rhel7
ec2_region: ap-southeast-2
ec2_ssh_key_name: Matho_SSH_Jan2021
ec2_vpc_subnet_id: subnet-0b84c8d601ee3257d  #Demo_Subnet
windows_ansible_connection: winrm
linux_server_name: LinuxSvr
win_server_name: WinSvr
app_name: "Default App"
root_user: ec2-user
windows_deploy_count: 2


public_dns_zone: mathodemos.com


# Windows WINRM connection parameters
ansible_winrm_transport: "basic"   #credssp for Tower 3.7
ansible_winrm_server_cert_validation: "ignore"
ansible_winrm_operation_timeout_sec: 120
ansible_winrm_read_timeout_sec: 150


